<?php

/**
 * @file
 * Contains student.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function student_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {

        case 'help.page.student':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('With this module you can collect information about your 
            students and display.') . '</p>';
            return $output;

        default:
    }
}

function student_theme() {
    return [
        'student_description' => [
            'template' => 'description',
            'variables' => [],
        ],
    ];
}